"""Added user permisions

Revision ID: 1ce90b6fc2b8
Revises: 3524c7ba87c3
Create Date: 2017-01-14 13:15:23.785571

"""

# revision identifiers, used by Alembic.
revision = '1ce90b6fc2b8'
down_revision = '3524c7ba87c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_default', 'roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
