"""empty message

Revision ID: 1cfe4410f69e
Revises: c0cb1285723
Create Date: 2017-01-15 01:25:25.057631

"""

# revision identifiers, used by Alembic.
revision = '1cfe4410f69e'
down_revision = 'c0cb1285723'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
