"""Initial migartion

Revision ID: 3341078f4de8
Revises: None
Create Date: 2017-01-12 00:26:02.210282

"""

# revision identifiers, used by Alembic.
revision = '3341078f4de8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
