"""Added confirmation tokens

Revision ID: 3524c7ba87c3
Revises: 1deb3e1ef41c
Create Date: 2017-01-14 03:12:43.789569

"""

# revision identifiers, used by Alembic.
revision = '3524c7ba87c3'
down_revision = '1deb3e1ef41c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
