"""Added user permisions

Revision ID: c0cb1285723
Revises: 1ce90b6fc2b8
Create Date: 2017-01-14 13:17:27.488286

"""

# revision identifiers, used by Alembic.
revision = 'c0cb1285723'
down_revision = '1ce90b6fc2b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
