"""empty message

Revision ID: 1d0ca77b42dc
Revises: 43e1b3a66819
Create Date: 2017-08-07 16:21:27.760717

"""

# revision identifiers, used by Alembic.
revision = '1d0ca77b42dc'
down_revision = '43e1b3a66819'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phonenumber', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phonenumber')
    ### end Alembic commands ###
