"""empty message

Revision ID: 30298841d2b5
Revises: 4909ec2f810a
Create Date: 2017-02-10 21:09:51.366926

"""

# revision identifiers, used by Alembic.
revision = '30298841d2b5'
down_revision = '4909ec2f810a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
