"""empty message

Revision ID: 3e8d59e6402
Revises: 30298841d2b5
Create Date: 2017-02-11 01:02:55.674388

"""

# revision identifiers, used by Alembic.
revision = '3e8d59e6402'
down_revision = '30298841d2b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
